# Nome da aplicacao
spring.application.name=sistema-automotivo-crud

# Porta da API
server.port=8080

# Configuracao do banco MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_automotivo?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Gustavoc1922
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Erros da API
server.error.include-message=always
server.error.include-binding-errors=always
